### ISSUE TITLE
Crash while loading on Forge 35.0.18 (1.16.4) due missing license info in mods.toml

### ISSUE THREAD

**Issue by yurifel** [Rongmario/GottaClimbFast#1]
The mod fails to load on the latest Forge version due to new requirements to include license info in the mods.toml file.  Crash report and example attached.

[crash-2020-11-18_13.23.34-fml.txt](https://github.com/Rongmario/GottaClimbFast/files/5562334/crash-2020-11-18_13.23.34-fml.txt)
[mods_toml.txt](https://github.com/Rongmario/GottaClimbFast/files/5562345/mods_toml.txt)

**Comment by Rongmario** [comment]
Use [1.1.](https://www.curseforge.com/minecraft/mc-mods/gotta-climb-fast/files/3061949)
