### ISSUE TITLE
Requires Minecraft 1.17?

### ISSUE THREAD

**Issue by ProsperCraft** [Rongmario/GottaClimbFast#2]
A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: gottaclimbfast requires {minecraft @ [1.17-alpha.20.45.a]}

gottaclimbfast-mc20w45a-2.0-fabric.jar
--

when trying to load with 1.16.4

**Comment by Rongmario** [comment]
That's the latest for the snapshot `20w45a`, its listed as '1.16.4' on curseforge as there's no '1.17' version selection available yet.
